{{- range $service := list "auth-service" "user-service" "payment-service" "notification-service" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service }}
  labels:
    app: {{ $service }}
spec:
  replicas: {{ index $.Values $service "replicaCount" }}
  selector:
    matchLabels:
      app: {{ $service }}
  template:
    metadata:
      labels:
        app: {{ $service }}
    spec:
      containers:
      - name: {{ $service }}
        image: "{{ $.Values.global.image.registry }}/{{ index $.Values $service "image" "repository" }}:{{ $.Values.global.image.tag }}"
        imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
        ports:
        - containerPort: {{ index $.Values $service "service" "port" }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ index $.Values $service "service" "port" }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: {{ index $.Values $service "service" "port" }}
          initialDelaySeconds: 10
          periodSeconds: 5
{{- end }}
